# Generated by Django 5.2.5 on 2026-08-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('software', 'Software Product'), ('website', 'Website Development'), ('portfolio', 'Portfolio Website'), ('career', 'Career Service'), ('it', 'IT Solution')], max_length=20)),
                ('short_description', models.CharField(max_length=300)),
                ('client_name', models.CharField(blank=True, help_text='Leave blank when the client name should remain private.', max_length=160)),
                ('image_url', models.URLField(blank=True, help_text='Optional public screenshot or image URL.')),
                ('project_url', models.URLField(blank=True, help_text='Optional live project URL.')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('coming_soon', 'Coming Soon')], default='completed', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Showcase',
                'verbose_name_plural': 'Project Showcase',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
