# Generated by Django 5.2.5 on 2026-08-05 01:53

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_projectshowcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectshowcase',
            name='full_description',
            field=models.TextField(blank=True, help_text='Optional detailed project description.'),
        ),
        migrations.AlterField(
            model_name='projectshowcase',
            name='image_url',
            field=models.URLField(blank=True, help_text='Old external image URL. Optional.'),
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Example: Dashboard, Accounting, Mobile View.', max_length=160)),
                ('media_type', models.CharField(choices=[('image', 'Screenshot / Image'), ('video', 'Screen Recording / Video')], default='image', max_length=10)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='screenshot')),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='screen recording')),
                ('is_cover', models.BooleanField(default=False, help_text='Select one screenshot as the project cover.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='website.projectshowcase')),
            ],
            options={
                'verbose_name': 'Project Media',
                'verbose_name_plural': 'Project Media',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
